### ISSUE TITLE
build issues with latest Qt

### ISSUE THREAD

**Issue by Himeko7** [ProtozeFOSS/KrakenZPlayground#3]
Trying to build this with latest Qt release, I get these errors:

offscreen_appcontroller.cpp:

245: mRenderControl->initialize(mGLContext); 
D:\Kraken\offscreen_appcontroller.cpp:245: error: Too many arguments to function call, expected 0, have 1

249: mOffscreenWindow->setRenderTarget(mFBO);
D:\Kraken\offscreen_appcontroller.cpp:249: error: Reference to incomplete type 'const QQuickRenderTarget' could not bind to an lvalue of type 'QOpenGLFramebufferObject *'

**Comment by Tpimp** [comment]
What platform? Opengl is required at the moment for the off screen rendering but it could be adapted to other RHIs in time.

**Comment by Himeko7** [comment]
Windows 11, Qt Creator 7.0.0
