### ISSUE TITLE
Edited Example...

### ISSUE THREAD

**Issue by stuu3k** [ProtozeFOSS/KrakenZPlayground#5]
Hey,

I have ripped apart and made my own version of one of your examples, happy to fork and share it if I can work out how, but I don't want to upset anyway by reusing their work, I.E. Background image and their code, here's what I have so far...

![image](https://user-images.githubusercontent.com/98365629/170999749-ab7e33d1-68e5-408a-b242-923d1814b497.png)

If I share this is that ok or not?!

Thanks

**Comment by Tpimp** [comment]
Always welcome to share!
